import React, {useState} from 'react';
import styles from '../styles/Navigator.module.css'
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faCog, faHistory, faHome} from "@fortawesome/free-solid-svg-icons";
import ActiveLink from "./ActiveLink";
import {useRouter} from 'next/router'
import Head from "next/head";
import styleDashboard from '../styles/Dashboard.module.css'
export default function Navigator(props) {
    const [nav, setNav] = useState('');
    const [hidden, setHidden] = useState(false);
    const toggleMenu = () => {
        setHidden(!hidden);
    };
    const router = useRouter()
    const handleClick = (e) => {
        e.preventDefault()
        router.push(e.target.href)
    }
    var wrapper = hidden ? styles.active : '';
    return (
        <div className={styles.wrapper + ' ' + wrapper}>
            <Head>
                <title>{props.active}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.sidebar}>
                <div className={styles.bg_shadow} onClick={toggleMenu}/>
                <div className={styles.sidebar__inner}>
                    <div className={styles.close} onClick={toggleMenu}>
                        <i className="fas fa-times"/>
                    </div>
                    <div className={styles.profile_info + ' ' + styles.info}>
                        <div className={styles.profile_img}>
                            <i className="fas fa-user-circle"/>
                        </div>
                        <div className={styles.profile_data}>
                            <p className={styles.name}>Welcome John</p>
                        </div>
                    </div>
                    <div className={styles.profile_info + ' ' + styles.device}>
                        <div className={styles.profile_data}>
                            <p className={styles.name}><i className="fas fa-laptop-house"/>&nbsp;Device Manager</p>
                        </div>
                    </div>
                    <ul className={styles.siderbar_menu}>
                        <li><a className={props.active === 'Dashboard' ? styles.active : ' '} href="Dashboard"
                               onClick={handleClick}><FontAwesomeIcon icon={faHome}/>&nbsp;Dashboard</a></li>
                        <li><a className={props.active === 'Log' ? styles.active : ' '} onClick={handleClick}
                               href="Log"><FontAwesomeIcon icon={faHistory}/>&nbsp;Logs</a>
                        </li>
                        <li><a className={props.active === 'Login' ? styles.active : ' '} onClick={handleClick}
                               href="Login"><FontAwesomeIcon icon={faCog}/>&nbsp;Setting</a></li>
                    </ul>

                </div>
            </div>
            <div className={styles.main_container}>
                <div className={styles.top_navbar}>
                    <div className={styles.hamburger} onClick={toggleMenu}>
                        <div className={styles.hamburger__inner}>
                            <i className="fas fa-bars"/>
                        </div>
                    </div>
                    <ul className={styles.menu}>
                    </ul>
                    <ul className={styles.right_bar}>
                        <li><i className="fas fa-user-circle"/></li>
                        <li>
                            <p className={styles.name}>Welcome John</p>
                        </li>
                    </ul>
                </div>
                <div className={styles.container}>
                    {props.component}
                </div>
                <div  className={styleDashboard.containerChart}>
                    {props.componentChart}
                </div>
            </div>
        </div>
    );
}